### ISSUE TITLE
Start-Select returns to x-1 instead of map tile you entered

### ISSUE THREAD

**Issue by Arnethegreat** [Arnethegreat/yoshis-funland-randomizer#1]
Beating 1-3 (world map) and going back into and start-select takes you to 1-1 in world map

**Comment by jpnance** [comment]
This is more subtle than described. When you start-select out of a level, the game tries to return you to that level's real tile within the same world but it has to be an exact match. If you're on the World 1 screen and you enter the fourth level, which happens to be 1-2, start-selecting out of it will put the cursor onto the normal 1-2 tile (i.e. the second level). If, instead, the fourth level were something else not in World 1, 2-8, for instance, the game isn't able to exactly match the tile you're supposed to be at and so it just defaults you to 1-1.

**Comment by Arnethegreat** [comment]
Redid hijacks and fixed issue hopefully for good
